name = 'erenonal'
main = "workers-site/index.js"  # Updated entry point
compatibility_date = "2025-04-26"
assets = { directory = "./out" }

[env.production]
workers_dev = false
routes = [
    "erenonal.com/*",
    "www.erenonal.com/*"
]

[env.staging]
workers_dev = true