name = 'personal-website'
main = "workers-site/index.js"  # Updated entry point
compatibility_date = "2024-05-01"

[site]
bucket = "./out"  # Your Next.js static export directory

[env.production]
workers_dev = false
routes = [
    "erenonal.com/*",
    "www.erenonal.com/*"
]

[env.staging]
workers_dev = true