name = "erenonal-website"
compatibility_date = "2024-05-01"

[site]
bucket = "./out"  # Your Next.js static files
entry-point = "workers-site"  # Special entry for static sites

[env.production]
workers_dev = false
routes = [
    "erenonal.com/*",
    "www.erenonal.com/*"
]

[env.staging]
workers_dev = true